# Generated by Django 5.0.4 on 2024-04-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_elder_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='Default_First_Name', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(default='Default_Gender', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='Default_Last_Name', max_length=255),
        ),
    ]
